### PR TITLE
added zerm

### PR DESCRIPTION
**Pull request by ejmg**
Hi there :wave: 

I've ported a theme over from Hugo named [zerm](https://github.com/ejmg/zerm). I say port because I consider it ~90-95% faithful to the original, [Terminal](https://github.com/panr/hugo-theme-terminal), with only minor deviations. I will be adding features and improving the port as I work with my [own blog](https://ageof.info), which is now built with Zola (thank you for making it, @Keats!).

Please let me know if there are any changes required before it will be accepted. I think the config file is well documented for how to use the theme along with the example content I have on the demo page being currently used in the readme.

### CODE REVIEW

**Comment by Keats** [comment]
Looks nice! I believe you can update the theme.toml to have https://zerm.ejmg.now.sh/ as demo no?

**Comment by ejmg** [comment]
Totally missed that, [i've pushed it](https://github.com/ejmg/zerm/commit/e5757ff2a28249f984045171dc8055b3262aa3ca) up into master along with a missing rss flag within config.toml. Anything else you'd like to see?

**Comment by Keats** [comment]
None, thanks!

**Comment by ejmg** [comment]
No, thank you! Love Zola and appreciate all of your effort to build out and maintain this project :slightly_smiling_face:

**Pull request merged**
