### PR TITLE
Fix theme submodules

### PR DESCRIPTION
**Pull request by Jieiku**
This fixes the following theme submodules:

- emily
- hermit
- hephaestus
- nasm-theme
- zolastrap
- zhuia

### CODE REVIEW

**Comment by Keats** [comment]
Something I would like to check before merging that is whether the themes are updated. If they are not I don't really want to show them on the zola website. I'm wondering what's the best way to do that, maybe try to build the demo site of each?

**Comment by Jieiku** [comment]
Just give me a list of which ones you want.... some of these themes look stellar even if they have not been updated in a while.

**Comment by Jieiku** [comment]
What you may eventually need to do is have your script check which themes are getting the most attention.... be that stars, contributors, combination of both, and sort the list of themes accordinly, putting the cream of the crop at the top, or like you said just be selective in which ones you include...

**Comment by Jieiku** [comment]
Do you mean that some of the themes may no longer build?? I assumed the generate script checked that... if thats what you mean then i totally get what your saying.

**Comment by Keats** [comment]
> Do you mean that some of the themes may no longer build?? I assumed the generate script checked that... if thats what you mean then i totally get what your saying.

Exaclty, if the themes hasn't been updated in 2 years for example, it's unlikely to still work. Thinking about it a bit more, I'll handle that later - no need to block this PR.

**Pull request merged**
