### PR TITLE
Particle theme

### PR DESCRIPTION
**Pull request by svavs**
Adding a new theme port

### CODE REVIEW

**Comment by Keats** [comment]
I missed this sorry.
https://particle.vercel.app/ doesn't seem to work?

**Comment by svavs** [comment]
The correct link is https://particle-zola.vercel.app/
Where do you found that link?

**Comment by Keats** [comment]
https://github.com/svavs/particle-zola/blob/master/theme.toml#L6

**Comment by svavs** [comment]
Sorry for the inconvenience. The file is now updated. Thank you.

**Comment by Keats** [comment]
Thanks!

**Pull request merged**
