### PR TITLE
Add zola-pickles theme

### PR DESCRIPTION
**Pull request by lukehsiao**
This is a rough port of the hugo pickles theme to Zola.

### CODE REVIEW

**Comment by Keats** [comment]
I like it; thanks!

**Comment by lukehsiao** [comment]
I noticed that this theme hasn't been put onto https://www.getzola.org/themes/ quite yet. What's the process like to get it on the actual theme site?

**Comment by Keats** [comment]
That's my fault, it's a manual process I keep forgetting to do. I need to integrate to have some CI o something setup that does it automatically

**Comment by Keats** [comment]
It's live now

**Pull request merged**
