### PR TITLE
Add Terminimal theme

### PR DESCRIPTION
**Pull request by pawroman**
Add my Terminimal theme.

### CODE REVIEW

**Comment by Keats** [comment]
Nice, thanks!

**Comment by pawroman** [comment]
Hi @Keats -- despite this being merged, my theme doesn't show up here: https://www.getzola.org/themes/ -- is there something wrong with my repository/metadata? Thanks

**Comment by Keats** [comment]
It's showing up now, I didn't merge the PR that adds it to the site

**Comment by pawroman** [comment]
Thanks! Both for merging and for creating such a great static site generator in the first place :smile:

**Pull request merged**
