### PR TITLE
Added Inky theme

### PR DESCRIPTION
**Pull request by jimmyff**

### CODE REVIEW

**Comment by Keats** [comment]
Have you figured out all the issues with your site with the `next` branch of Zola?

**Comment by Jieiku** [comment]
Clean looking theme, looks like it may be affected by the bug I reported here: https://github.com/getzola/zola/issues/1856

**Comment by jimmyff** [comment]
@Keats ah no I didn't know that was a thing, I'll get it working with the `next` build. As there are breaking changes mentioned how can I specify the theme's minimum zola version? Maybe a `zola_version` would be a good addition to the [config](https://www.getzola.org/documentation/getting-started/configuration/)?

@Jieiku thanks for flagging that, I'll look through the fix you've linked me to and update as required!

**Comment by jimmyff** [comment]
> There is `min_version`: https://www.getzola.org/documentation/themes/creating-a-theme/

🤦‍♂️ thanks! ☺️

**Comment by jimmyff** [comment]
Hey @Keats I've made it compatible with the next branch but I'm struggling to get the build working. I've tried to set this in my deploy script: `uses: shalzz/zola-deploy-action@next` but it's not happy:
https://github.com/jimmyff/zola-inky/actions/runs/4157851465/jobs/7192645103

**Pull request merged**
