### PR TITLE
added kangae microblog theme

### PR DESCRIPTION
**Pull request by ayushnix**

### CODE REVIEW

**Comment by Jieiku** [comment]
HAH! Love it!

**Comment by ayushnix** [comment]
> HAH! Love it!

Thanks! 😄

**Comment by ayushnix** [comment]
Looks like the CI job failed because the [simplify theme](https://github.com/getzola/themes/runs/6340608656?check_suite_focus=true#step:2:199) wasn't found.

**Comment by ayushnix** [comment]
Let me know if I should add a commit to remove the simplify theme.

**Comment by Keats** [comment]
Yes please

**Comment by ayushnix** [comment]
Done

**Pull request merged**
