### PR TITLE
Add juice theme

### PR DESCRIPTION
**Pull request by Folyd**
**Juice** is an intuitive, elegant, and responsive Zola™ theme for product sites.

- Build for product sites
- Simple and intuitive structure
- Clean and elegant design 
- Responsive and mobile device compatible
- Customize and extend friendly

https://juice.huhu.io

### CODE REVIEW

**Comment by Keats** [comment]
Looking good! I don't have a trademark on Zola though ;)

**Comment by Folyd** [comment]
@Keats Thanks. I'll remove the trademark. Haha 😄

**Comment by Folyd** [comment]
@Keats BTW, how can my theme will be shown in this page? https://www.getzola.org/themes/

**Comment by Keats** [comment]
Looks like there is an issue with the GH action that does PR, I'll have a look.

**Pull request merged**
