### PR TITLE
Add simple dev blog theme

### PR DESCRIPTION
**Pull request by bennetthardwick**
I've converted my old Gatsby site into this simple _optimised_ dev blog theme, you can try it out [here](https://simple-dev-blog-zola-starter.netlify.app/):
<details>
  <summary>Screenshot</summary>
  
</details>

Thanks!

### CODE REVIEW

**Comment by bennetthardwick** [comment]
Hey @Keats, any chance you could take a look?

**Comment by Keats** [comment]
Oops sorry. I've released 0.11 yesterday - can you check if it works well with it?
For a blog theme, you probably want to set up some feed.

**Comment by bennetthardwick** [comment]
No worries, I'll update it now and add rss.

**Comment by bennetthardwick** [comment]
Hey @Keats I've tested locally and it works great. :+1: You can see it [here](https://simple-dev-blog-zola-starter.netlify.app/) (/atom.xml is there as well now)

**Comment by Keats** [comment]
Great thanks!

**Comment by Keats** [comment]
You need to move to take a screenshot and put it at the root of the repo as `screenshot.png`

**Pull request merged**
