### PR TITLE
added hephaestus theme

### PR DESCRIPTION
**Pull request by BConquest**

### CODE REVIEW

**Comment by Keats** [comment]
I don't know if it's intended but you probably want the footer on https://bryantconquest.com/ to stick to the bottom no?
Either with some 
```
position: fixed;
bottom: 0;
```
or some flexbox column spacing.

**Comment by BConquest** [comment]
I thought it would be best if it just appears at the bottom of the site after all of the content. I could change it to always be visible(attached to the bottom), but I think that the site wouldn't flow as well.

**Comment by BConquest** [comment]
I have made the footer take up the same width as the other sections of the webpage. I also made the source for the theme to be more "default" by removing refrences to me, are there any other recommendations?

**Comment by Keats** [comment]
You should probably move https://github.com/BConquest/hephaestus/blob/main/theme.toml#L17-L22 to your config.toml rather than theme.toml, otherwise the theme users will get your social links by default. You can just mention that the existence of those in the README

**Comment by BConquest** [comment]
I have removed those social sites and also changed the template pages to be more generic and only have filler text. Sorry for all the commits haven't worked with submodules before. There anything else that needs to be changed, and I will be adding something to the main page just not shure what it will be yet.

**Comment by Keats** [comment]
I think it's ok, let's see if it manages to build the site. I should really have the CI try to build it...

**Pull request merged**
