### PR TITLE
Add after-after-dark theme

### PR DESCRIPTION
**Pull request by micahkepe**
Enhancements to the original `after-dark` theme, including:
- Fancy codeblock with clipboards
- LaTex support
- Search index/ search bar functionality

Demo: https://micahkepe.com/blog/

### CODE REVIEW

**Comment by Keats** [comment]
Could some of that be added to the after-dark theme as options instead?

**Comment by micahkepe** [comment]
Which options were you thinking could be added to the original theme? I was originally thinking of creating this as a separate theme from the original I plan to add at least these features/changes to this theme in the future to further differentiate it from `after-dark` (which I love by the way thank you so much for the work you did on that @Keats):
- Light/Dark modes
- Different font (probably closer to the font in the `archie` or `apollo` themes)
- Optional footer with links to socials/ contact

**Comment by Keats** [comment]
I think most of those can be options, but it's really up to you

**Comment by micahkepe** [comment]
Went ahead and made a pull request to the original `after-dark` repo. I will continue to work on my custom theme independently in the future to differentiate it more from `after-dark`.

**Pull request closed without merging**
