### PR TITLE
GitHub action for publishing themes gallery

### PR DESCRIPTION
**Pull request by zbrox**
I tested this with another repo and seems to work.

Here's a breakdown of its actions:
- initialzes this repo and submodules
- runs generator script to produce themes gallery in a folder called `site`
- saves an artifact of the generated gallery in the running github action
- clones `getzola/zola` in a folder called `zola`
- copies the contents of `site` in `zola/docs/content/themes`
- cd's in the `zola` folder, sets the commit author name and email and creates a commit with the message "Update themes gallery"
- pushes to `getzola/zola`

For this to work a secret needs to be added in the settings of the themes repository with the name TOKEN. Here's [the documentation](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line) on creating personal access tokens.

Btw I'm sorry but I have no idea why the older commits are showing in this pull request, since the fork seems to be in sync.

### CODE REVIEW

**Comment by Keats** [comment]
Is it easy to make it do a PR on master instead? I'd like to check the output before merging.

**Comment by zbrox** [comment]
Yeah that should be doable. There’s one thing that might be an issue (the origin repo of the pull request) but I’ll give it a go on Sunday probably.

**Comment by zbrox** [comment]
Hey, sorry for the big delay. I tested this on a separate repository and seems to be working as expected.

**Comment by Keats** [comment]
Thanks, sorry for the late comment. I've added the TOKEN access token, let's see how it goes.

**Comment by zbrox** [comment]
I tested the approach on a private repo I have on GitHub and it worked out fine. There can be some tweaking on the messages and the naming of the pull requests but apart from that it went well.

**Comment by zbrox** [comment]
Ah, I found a bug in the extra check I added for metadata in the generate script. A pretty stupid one :) sorry about that. I'll make another pull request for fixing that.

**Pull request merged**
