### PR TITLE
Update themes

### PR DESCRIPTION
**Pull request by Keats**

### CODE REVIEW

**Comment by welpo** [comment]
Hi,

Was this supposed to update all themes? I see some are missing from the commit (like tabi).

Even Abridge, which is on the commit, still shows an older README text on the site.

On a related note, what are the steps to send a PR to update the themes? Would this work?

**Step 1**:
```bash
# Fork and clone this repo
git submodule update --init --recursive
   git submodule update --remote --merge
   git commit -am "Update All Submodules"
   ```

**Step 2**: Create a PR with this commit in this repo. (It'd look like this https://github.com/welpo/themes/commit/13a44b43395d613876893e854045fff7c3bc1d0a)

**Step 3**:

    ```bash
    python generate_docs.py /tmp/docs
    ```

And use this output to create a PR to the main Zola repo, in this directory: https://github.com/getzola/zola/tree/master/docs/content/themes

Is this correct? I'd gladly help update the themes docs if I knew how to.

**Comment by Jieiku** [comment]
I do this as part of my bash script that generates this page: https://github.com/Jieiku/zola-themes-benchmarks/blob/main/README.md

This allows me to scrape each submodule for relevant info (and new themes), here is how I update:

```bash
git clone https://github.com/getzola/themes
cd ~/.dev/themes

git submodule foreach --recursive git reset --hard
git reset --hard

git pull
git submodule update --init --recursive
git submodule update --remote --merge

mkdir -p ~/themes-docs
python generate_docs.py ~/themes-docs
```

The above updates all the submodules, but the generate_docs.py command just ouputs to a folder that I created... so I am not so sure about that part. (would think those generated docs need to go someplace as part of a new git commit.)

**Comment by Keats** [comment]
I didn't merge https://github.com/getzola/zola/pull/2279 yet, doing it now

**Comment by welpo** [comment]
I see, thanks for the reply.

I noticed https://github.com/getzola/zola/pull/2279 hasn't actually updated my theme's (tabi) info. Both the `README.md` and the `theme.toml` seem to have been ignored.

Any idea why that might be? If I build the docs manually, it looks fine.

**Comment by Keats** [comment]
Not sure, git doesn't seem to pick up the changes in that repo for some reason?

**Comment by welpo** [comment]
Hm. Any suggestions as to how I can begin troubleshooting this? The GitHub action logs appear to show a successful connection to my repo.

In the meantime, would it be acceptable for me to do a manual PR with the updated docs?

**Comment by Keats** [comment]
I'll have a look tonight

**Comment by welpo** [comment]
Any updates, @Keats? Any way I can help?

**Comment by Keats** [comment]
Sorry, I won't have time these upcoming weeks. It's just a matter of checking what git says though

**Comment by welpo** [comment]
I can't figure out why your commit didn't pick up the changes on my theme.

Since I can update it just fine following https://github.com/getzola/themes#updating-all-themes, I'll open a PR to update all themes.

**Pull request merged**
