### PR TITLE
Add karzok theme

### PR DESCRIPTION
**Pull request by kogeletey**
My documentation theme

### CODE REVIEW

**Comment by Keats** [comment]
It looks like it cannot check it out?

**Comment by kogeletey** [comment]
I'm sorry. The work on this project just started, and I rolled back to another version. We'll fix everything now)

**Comment by kogeletey** [comment]
Is something wrong?

**Comment by Keats** [comment]
Looks like git still can't checkout the theme

**Comment by kogeletey** [comment]
Hmm, strange 
image

**Comment by kogeletey** [comment]
It seems to have been fixed)

**Comment by Keats** [comment]
Thanks!

**Pull request merged**
